spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG

