spring:
  application:
    name: auth-service
  config:
    import: optional:configserver:http://localhost:6090
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    org.mongodb.driver: DEBUG

